# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/bravenash: container
    io.kubernetes.cri-o.ContainerType/stoichawking: container
    io.kubernetes.cri-o.SandboxID/bravenash: aad209ce86cffdb84fe4767a111b9d71b50ddcfe09cfb4d7283fa84ff9d4bd7
    io.kubernetes.cri-o.SandboxID/stoichawking: aad209ce86cffdb84fe4767a111b9d71b50ddcfe09cfb4d7283fa84ff9d4bd7
    io.kubernetes.cri-o.TTY/bravenash: "true"
    io.kubernetes.cri-o.TTY/stoichawking: "true"
    io.podman.annotations.autoremove/bravenash: "FALSE"
    io.podman.annotations.autoremove/stoichawking: "FALSE"
    io.podman.annotations.init/bravenash: "FALSE"
    io.podman.annotations.init/stoichawking: "FALSE"
    io.podman.annotations.privileged/bravenash: "FALSE"
    io.podman.annotations.privileged/stoichawking: "FALSE"
    io.podman.annotations.publish-all/bravenash: "FALSE"
    io.podman.annotations.publish-all/stoichawking: "FALSE"
  creationTimestamp: "2023-01-22T17:10:42Z"
  labels:
    app: gdi
  name: gdi
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - postgres
    image: docker.io/edigonzales/postgis:14-3.2
    name: stoichawking
    env:
    - name: POSTGRES_DB
      value: pub
    - name: POSTGRES_PASSWORD
      value: mysecretpassword
    - name: POSTGRES_HOST_AUTH_METHOD
      value: md5
    - name: PG_WRITE_PWD
      value: ddluser
    - name: PG_READ_PWD
      value: dmluser
    - name: PG_GRETL_PWD
      value: gretl
    ports:
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 5432
      hostPort: 54322
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    tty: true
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: 8d65bc737579119ddb2570fb6fb50c85e672af58c9ef84ac321ff4dbbbf2f0fa-pvc
  - image: docker.io/edigonzales/geoserver:2.22.0
    name: bravenash
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    tty: true
  enableServiceLinks: false
  hostname: gdi
  restartPolicy: Never
  volumes:
  - name: 8d65bc737579119ddb2570fb6fb50c85e672af58c9ef84ac321ff4dbbbf2f0fa-pvc
    persistentVolumeClaim:
      claimName: 8d65bc737579119ddb2570fb6fb50c85e672af58c9ef84ac321ff4dbbbf2f0fa
status: {}

